install.packages(c('shiny', 'httr', 'jsonlite', 'lubridate', 'cowplot', 'CPAT', 'synchrony', 'forecast', 'zoo', 'readr', 'mgcv', 'remotes'), repos='https://cran.rstudio.com/')
remotes::install_version('textshaping', '0.3.6')
remotes::install_version('ragg', '1.2.5')
remotes::install_version('tidyverse', '2.0.0')
remotes::install_version('rsconnect', '0.8.29')
remotes::install_github('UCaromel/telraamStats')