name: Deploy to shinyapps.io

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger
  
env:
  GITHUB_PAT: ${{ secrets.TOKEN }}
  MY_KEY: ${{ secrets.MY_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R environment
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.x
    
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev

    - name: Install packages
      run: |
        R -e "install.packages(c('shiny', 'remotes'), repos='https://cran.rstudio.com/')"
        R -e "remotes::install_github('UCaromel/telraamStats')"
        R -e "remotes::install_version('rsconnect', '0.8.29')"

    - name: Deploy to shinyapps.io
      run: |
        Rscript -e "rsconnect::setAccountInfo(name=${{secrets.SHINY_ACCOUNT}}, token=${{secrets.SHINY_TOKEN}}, secret=${{secrets.SHINY_SECRET}})"
        Rscript -e "rsconnect::deployApp(appName = 'app_packagee')" 
